version: "3.7"

services:

  api:
    image: speedcal-api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    hostname: speedcal
    networks:
      - speedcal

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token 
    networks:
      - speedcal

networks:
  speedcal:
